version: '3.3'
services:
  web:
    build:
      context: ./phpapp
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - db
    volumes:
      - ./phpapp:/var/www/html/
    ports:
      # : mach :doc 
      - 8080:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql8
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin